### ISSUE TITLE
Criar também a alteração do imunidade ao coma para eAthena com eAMod

### ISSUE THREAD

**Issue by ElKowak** [carloshenrq/brAScript#1]
Link do github com o emulador em questão: [https://github.com/ElKowak/eAthena](url)

--- Edição: (Adicionado link onde começou o pedido do usuário)
https://github.com/carloshenrq/brAScript/commit/e4fc0b6a2a2a4e047ebbb32f4807225049047854#commitcomment-20871512

**Comment by carloshenrq** [comment]
Não existe um repositório oficial do eAthena com eAmod? Se for o caso, eu irei cobrar pela alteração.

**Comment by ElKowak** [comment]
é o mesmo emulador deste repositorio https://github.com/zephyrus-cr/eamod apenas separei ele dos outros

**Comment by carloshenrq** [comment]
Jovem, o emulador acima, é meio antigo :@
Código fonte desatualizado e tudo mais, fica complicado programar nele. Vai dar problema, e os testes ficam mais complicados.
Fazer downgrade de código é retrocesso...

Então... Não vou assumir essa responsabilidade ^~^
